spring.application.name=GerenciamentoDeEstoqueLSP

# Código de configuração do H2 Database

spring.datasource.url=jdbc:h2:mem:devDb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=lsp
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Parte que faz o hibernate criar e atualizar sozinho as "tabelas"
spring.jpa.hibernate.ddl-auto=update